<?php

namespace App\Imports;

use App\Models\Product;
use App\Models\ProductCategory;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithValidation;
use Maatwebsite\Excel\Concerns\SkipsOnError;
use Maatwebsite\Excel\Concerns\SkipsErrors;
use Maatwebsite\Excel\Concerns\SkipsOnFailure;
use Maatwebsite\Excel\Concerns\SkipsFailures;
use Maatwebsite\Excel\Concerns\WithBatchInserts;
use Maatwebsite\Excel\Concerns\WithChunkReading;
use Illuminate\Support\Facades\Log;

class ProductsImport implements
    ToModel,
    WithHeadingRow,
    WithValidation,
    SkipsOnError,
    SkipsOnFailure,
    WithBatchInserts,
    WithChunkReading
{
    use SkipsErrors, SkipsFailures;

    protected $rowCount = 0;
    protected $successCount = 0;

    public function model(array $row)
    {
        $this->rowCount++;

        // Skip empty rows
        if (empty($row['sku']) || empty($row['name'])) {
            Log::warning('Skipping empty row', ['row' => $this->rowCount]);
            return null;
        }

        try {
            // Check if product exists by SKU
            $product = Product::where('sku', $row['sku'])->first();

            // Find or create category
            $categoryId = null;
            if (!empty($row['category'])) {
                $category = ProductCategory::where('name', $row['category'])->first();
                if ($category) {
                    $categoryId = $category->id;
                } else {
                    Log::info('Category not found, will be set to null', ['category' => $row['category']]);
                }
            }

            // Prepare product data
            $data = [
                'name' => $row['name'],
                'barcode' => $row['barcode'] ?? null,
                'description' => $row['description'] ?? null,
                'category_id' => $categoryId,
                'cost' => !empty($row['cost']) ? floatval($row['cost']) : 0,
                'price' => floatval($row['price']),
                'unit_of_measure' => $row['unit_of_measure'] ?? 'pcs',
                'reorder_point' => !empty($row['reorder_point']) ? intval($row['reorder_point']) : 0,
                'reorder_quantity' => !empty($row['reorder_quantity']) ? intval($row['reorder_quantity']) : 0,
                'weight' => !empty($row['weight']) ? floatval($row['weight']) : null,
                'dimensions' => $row['dimensions'] ?? null,
                'notes' => $row['notes'] ?? null,
                'is_active' => $this->parseStatus($row['status'] ?? 'Active'),
            ];

            if ($product) {
                // Update existing product
                Log::info('Updating existing product', ['sku' => $row['sku']]);
                $product->update($data);
                $this->successCount++;
                return null; // Don't create new model
            }

            // Create new product
            // Don't set slug - let the model's boot method handle it
            Log::info('Creating new product', ['sku' => $row['sku']]);
            $this->successCount++;

            return new Product(array_merge($data, [
                'sku' => $row['sku'],
                // slug will be auto-generated by the model's boot method
            ]));
        } catch (\Exception $e) {
            Log::error('Error processing row ' . $this->rowCount, [
                'error' => $e->getMessage(),
                'row_data' => $row
            ]);
            throw $e;
        }
    }

    public function rules(): array
    {
        return [
            'sku' => 'required|string|max:255',
            'name' => 'required|string|max:255',
            'price' => 'required|numeric|min:0',
            'cost' => 'nullable|numeric|min:0',
            'barcode' => 'nullable|string|max:255',
            'weight' => 'nullable|numeric|min:0',
        ];
    }

    public function customValidationMessages()
    {
        return [
            'sku.required' => 'SKU is required',
            'name.required' => 'Product name is required',
            'price.required' => 'Price is required',
            'price.numeric' => 'Price must be a number',
            'cost.numeric' => 'Cost must be a number',
            'weight.numeric' => 'Weight must be a number',
        ];
    }

    public function batchSize(): int
    {
        return 50;
    }

    public function chunkSize(): int
    {
        return 50;
    }

    public function getRowCount(): int
    {
        return $this->rowCount;
    }

    public function getSuccessCount(): int
    {
        return $this->successCount;
    }

    private function parseStatus($status): bool
    {
        if (is_bool($status)) {
            return $status;
        }

        $status = strtolower(trim($status));
        return in_array($status, ['active', '1', 'yes', 'true']);
    }
}